name: CI/CD Pipeline

env:
  DOCKER_IMAGE_NAME: szaitman/maven-hello-world
  DOCKER_REGISTRY_USERNAME: szaitman
on:
  push:

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      # g_run_id: ${{ steps.set_ver.outputs.result }}
      my_output: ${{ steps.set_output.outputs.result }}

    defaults:
      run:
        working-directory: myapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Increment version
        run: mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{$3+=1; print $1"."$2"."$3}') -DgenerateBackupPoms=false

      - name: Get the current version 
        run: |
          new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "New version: $new_version"
          echo "DOCKER_IMAGE_TAG=$new_version" >> $GITHUB_ENV

      - name: Print Variable
        run: echo "DOCKER_IMAGE_TAG ${{ env.DOCKER_IMAGE_TAG }}"
          
      - name: Commit and push version bump
        run: |
          git config --global user.name 'zshuki'
          git config --global user.email 'zshuki@gmail.com'
          git add pom.xml
          git commit -m 'Increment minor version'
          git push
      # - name: set_ver
      #   # run: echo "g_run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
      #   # run: echo "::set-output g_run_id=result::${{ github.run_id }}"
      #   run: echo "::set-output name=result::${{ github.run_id }}"

      - name: Set output variable
        id: set_output
        run: echo "::set-output name=result::Hello from Job 1"


  build-and-push:
    runs-on: ubuntu-latest
    needs: increment-version
    defaults:
      run:
        working-directory: myapp
    steps:
      - uses: actions/checkout@v3

      - name: Use output from increment-version
        run: echo "Job 1 said ${{ needs.increment-version.outputs.my_output }}"
      # - name: Use g_run_id
      #   run: echo "g_run_id is - ${{ needs.increment-version.outputs.g_run_id }}"

      - name: Get the current version 
        run: |
          new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{$3+=1; print $1"."$2"."$3}')
          echo "New version: $new_version"
          echo "DOCKER_IMAGE_TAG=$new_version" >> $GITHUB_ENV
      
      - name: Build the Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Log in to Docker Registry
        run: docker login -u ${{ env.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push the Docker Image
        run: docker push  ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    defaults:
      run:
        working-directory: myapp
    steps:
      - uses: actions/checkout@v3

      - name: Use g_run_id
        run: echo "g_run_id is - ${{ needs.increment-version.outputs.g_run_id }}"

      - name: Get the current version 
        run: |
          new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{$3+=1; print $1"."$2"."$3}')
          echo "New version: $new_version"
          echo "DOCKER_IMAGE_TAG=$new_version" >> $GITHUB_ENV
  
      - name: Log in to Docker Registry
        run: docker login -u ${{ env.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull the Docker Image
        run: docker pull  ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Run Docker for test
        run: docker run ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Configure kubectl
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: delete job
  #       run: kubectl delete  -f deployment.yaml

  #     - name: Apply Kubernetes Manifest
  #       run: sed -e  "s/DOCKER_IMAGE_TAG/${{ env.DOCKER_IMAGE_TAG }}/" deployment.yaml | kubectl apply -f -

  #     - name: get pod info
  #       run: |
  #         sleep 30
  #         kubectl get pod | grep maven-hello-world | awk '{print $1}'
  #         kubectl logs $(kubectl get pod | grep maven-hello-world | awk '{print $1}')

  #     - name: cleanup
  #       run: kubectl delete  -f deployment.yaml

